version: 2.1

orbs:
  ta-go: travelaudience/go@0.3
  go: circleci/go@0.2.0

jobs:
  go_test:
    docker:
      - image: circleci/golang:1.13
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          race: true

  docker_build:
    machine: true
    steps:
      - checkout
      - run: docker build -t quay.io/travelaudience/prometheus-validator:${CIRCLE_TAG:-latest} .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD quay.io
      - run: docker push quay.io/travelaudience/prometheus-validator:${CIRCLE_TAG:-latest}

workflows:
  build_and_test:
    jobs:
      - ta-go/checks  # run static analysis against the code
      - go_test
      - docker_build:
          requires:
            - ta-go/checks
            - go_test
          filters:
            tags:
              only: /.*/
